version: '3.8'

services:
    nginx:
        build: ./nginx/
        container_name: nginx-container
        ports:
        - target: 80
          published: 80
          protocol: tcp
          mode: host
        links:
            - php
            - redis
        depends_on:
            - php
            - redis
        volumes:
            - .:/var/www/

    php:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: php-container
        expose:
            -   9000
        volumes:
            - .:/var/www/
        depends_on:
            -   db

    db:
        image: mysql:8.0
        container_name: db-container
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_DATABASE=admin
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=merlin
            - MYSQL_ROOT_PASSWORD=merlin
        volumes:
            - .:/var/www/
    redis:
        image: redis:latest
        container_name: redis-container
        restart: always
        ports:
            - "6379:6379"
        command: redis-server --save 60 1 --requirepass cacheme --loglevel warning
        volumes:
            -   .:/var/www/
